#!/bin/bash

sbt -DapplyEvolutions.default=true -Dcyan.password=test -Dslick.dbs.default.db.url="jdbc:postgresql://db/cyan" -Dslick.dbs.default.db.user=cyan -Dslick.dbs.default.db.password=secretpass run